import { db } from '@/lib/db';
import { eq, ne } from 'drizzle-orm';
import { products, categories, orders, inventory, coupons, refunds, conversations, messages } from '@/storage/database/shared/schema';
import { randomUUID } from 'node:crypto';

const DEMO_CATEGORIES = [
  { name: '商业咨询', name_en: 'Business Consulting', type: 'service' },
  { name: '技术顾问', name_en: 'Tech Advisory', type: 'service' },
  { name: '语言培训', name_en: 'Language Training', type: 'service' },
  { name: '数字模板', name_en: 'Digital Templates', type: 'virtual' },
  { name: '在线课程', name_en: 'Online Courses', type: 'virtual' },
  { name: '电子书籍', name_en: 'E-Books', type: 'virtual' },
];

const DEMO_PRODUCTS = [
  { title: '跨境电商战略咨询', title_en: 'Cross-Border E-Commerce Strategy', type: 'service', price: '299.00', duration: '60min', delivery_method: 'online', cat: '商业咨询' },
  { title: '市场进入策略分析', title_en: 'Market Entry Strategy', type: 'service', price: '499.00', duration: '90min', delivery_method: 'online', cat: '商业咨询' },
  { title: '品牌定位咨询', title_en: 'Brand Positioning', type: 'service', price: '199.00', duration: '45min', delivery_method: 'online', cat: '商业咨询' },
  { title: '网站开发顾问', title_en: 'Web Development Consulting', type: 'service', price: '399.00', duration: '60min', delivery_method: 'online', cat: '技术顾问' },
  { title: 'AI 应用落地指导', title_en: 'AI Implementation Guide', type: 'service', price: '599.00', duration: '120min', delivery_method: 'online', cat: '技术顾问' },
  { title: '网络安全评估', title_en: 'Cybersecurity Assessment', type: 'service', price: '349.00', duration: '60min', delivery_method: 'online', cat: '技术顾问' },
  { title: '商务葡语速成', title_en: 'Business Portuguese Crash Course', type: 'service', price: '249.00', duration: '45min', delivery_method: 'online', cat: '语言培训' },
  { title: '英语商务沟通', title_en: 'English Business Communication', type: 'service', price: '219.00', duration: '45min', delivery_method: 'online', cat: '语言培训' },
  { title: '商业计划书模板', title_en: 'Business Plan Template', type: 'virtual', price: '29.00', delivery_method: 'download', cat: '数字模板' },
  { title: '财务模型 Excel 模板', title_en: 'Financial Model Excel Template', type: 'virtual', price: '49.00', delivery_method: 'download', cat: '数字模板' },
  { title: '合同范本包', title_en: 'Contract Templates Pack', type: 'virtual', price: '39.00', delivery_method: 'download', cat: '数字模板' },
  { title: '跨境电商实战课程', title_en: 'Cross-Border E-Commerce Course', type: 'virtual', price: '199.00', delivery_method: 'email', cat: '在线课程' },
  { title: '数字营销全攻略', title_en: 'Digital Marketing Mastery', type: 'virtual', price: '149.00', delivery_method: 'email', cat: '在线课程' },
  { title: '非洲市场入门指南', title_en: 'African Market Entry Guide', type: 'virtual', price: '79.00', delivery_method: 'download', cat: '电子书籍' },
  { title: '国际贸易实务手册', title_en: 'International Trade Handbook', type: 'virtual', price: '89.00', delivery_method: 'download', cat: '电子书籍' },
];

export async function seedDemoData() {
  const categoryMap = new Map<string, string>();

  for (const cat of DEMO_CATEGORIES) {
    const id = randomUUID();
    await db.insert(categories).values({
      id,
      name: cat.name,
      name_en: cat.name_en || null,
      type: cat.type,
      sort_order: DEMO_CATEGORIES.indexOf(cat),
      is_active: true,
    });
    categoryMap.set(cat.name, id);
  }

  for (const prod of DEMO_PRODUCTS) {
    const catId = categoryMap.get(prod.cat);
    const id = randomUUID();
    await db.insert(products).values({
      // id auto-generated by DB default
      title: prod.title,
      title_en: prod.title_en || '',
      type: prod.type,
      price: prod.price,
      category_id: catId || '',
      seller_id: 'seed',
      status: 'active',
      duration: prod.duration || null,
      delivery_method: prod.delivery_method || null,
      description: `这是 ${prod.title} 的详细介绍。请联系我们获取更多信息。`,
      description_en: `Detailed description for ${prod.title_en}. Contact us for more information.`,
    });
  }

  const allProducts = await db.select({ id: products.id, type: products.type }).from(products);

  for (const p of allProducts) {
    const invId = randomUUID();
    await db.insert(inventory).values({
      id: invId,
      product_id: p.id,
      stock: p.type === 'virtual' ? 999 : 50,
      low_stock_threshold: 10,
    });
  }

  return { categories: DEMO_CATEGORIES.length, products: DEMO_PRODUCTS.length };
}

export async function clearDemoData() {
  const tableNames = [
    'inventory_transactions', 'inventory',
    'order_items', 'orders',
    'product_reviews', 'product_recommendations',
    'wishlist_items',
    'email_logs', 'abandoned_carts',
    'audit_logs', 'page_views',
    'stock_transfers', 'messages', 'conversations',
    'refunds', 'coupons',
    'user_memberships',
  ];

  // Use raw SQL for table-level deletes since these are dynamic table names
  for (const table of tableNames) {
    await db.$client.execute(`DELETE FROM ${table}`);
  }

  // 删除商品（保留分类）
  await db.delete(products); // Delete all products

  // 删除演示分类
  for (const cat of DEMO_CATEGORIES) {
    await db.delete(categories).where(eq(categories.name, cat.name));
  }

  return { cleared: true };
}
